import 'dart:async';
import 'dart:typed_data';
import 'package:camera/camera.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';
import '../../../core/network/api_client.dart';
import '../../../core/theme/app_theme.dart';
class RecordingSessionPage extends StatefulWidget { final String? orderId; final String? warehouseId; const RecordingSessionPage({super.key, this.orderId, this.warehouseId}); @override State<RecordingSessionPage> createState()=>_RecordingSessionPageState(); }
class _RecordingSessionPageState extends State<RecordingSessionPage>{
 static const segmentDuration=Duration(seconds:45); CameraController? _cam; Timer? _segmentTimer; bool _camReady=false,_recording=false,_busy=false,_rolling=false; String? _recordingId,_error,_status; Duration _elapsed=Duration.zero; DateTime? _startedAt; int _nextSequence=0; final List<Future<void>> _pending=[];
 @override void initState(){super.initState();_initCamera();} @override void dispose(){_segmentTimer?.cancel();_cam?.dispose();super.dispose();}
 Future<void> _initCamera()async{try{if(!kIsWeb){final s=await Permission.camera.request();if(!s.isGranted){if(mounted)setState(()=>_error='Camera permission denied');return;}}final cams=await availableCameras();if(cams.isEmpty){if(mounted)setState(()=>_error='No camera found');return;}final back=cams.firstWhere((c)=>c.lensDirection==CameraLensDirection.back,orElse:()=>cams.first);final c=CameraController(back,ResolutionPreset.medium,enableAudio:true);await c.initialize();if(!mounted)return;setState((){_cam=c;_camReady=true;});}catch(e){if(mounted)setState(()=>_error='Camera: $e');}}
 Future<void> _toggle()async{if(_busy)return;if(_recording)await _stop();else await _start();}
 Future<void> _start()async{setState((){_busy=true;_error=null;_status=null;});try{String? orderId=widget.orderId,warehouseId=widget.warehouseId;if(orderId==null||warehouseId==null){final or=await ApiClient.instance.dio.get('/orders');final ob=or.data;final ol=ob is Map&&ob['data'] is List?ob['data'] as List:(ob is List?ob:<dynamic>[]);if(ol.isNotEmpty)orderId??=(ol.first as Map)['id']?.toString();final wr=await ApiClient.instance.dio.get('/warehouses');final wb=wr.data;final wl=wb is Map&&wb['data'] is List?wb['data'] as List:(wb is List?wb:<dynamic>[]);if(wl.isNotEmpty)warehouseId??=(wl.first as Map)['id']?.toString();}if(orderId==null||warehouseId==null)throw Exception('Need orderId + warehouseId');final res=await ApiClient.instance.dio.post('/recordings/start',data:{'orderId':orderId,'warehouseId':warehouseId});final body=res.data;final data=body is Map&&body['data']!=null?body['data']:body;final id=data is Map?data['id']?.toString():null;if(id==null)throw Exception('Recording id missing');_recordingId=id;_startedAt=DateTime.now();_nextSequence=0;await _startCameraSegment();setState((){_recording=true;_elapsed=Duration.zero;});_scheduleRollover();_tick();}on DioException catch(e){if(mounted)setState(()=>_error=e.message??'Start failed');}catch(e){if(mounted)setState(()=>_error='$e');}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _startCameraSegment()async{if(_cam==null||!_cam!.value.isInitialized)throw Exception('Camera not ready');if(!_cam!.value.isRecordingVideo)await _cam!.startVideoRecording();}
 void _scheduleRollover(){_segmentTimer?.cancel();_segmentTimer=Timer(segmentDuration,_rollover);}
 Future<void> _rollover()async{if(!_recording||_rolling)return;_rolling=true;try{final seq=_nextSequence++;XFile? file;if(_cam!.value.isRecordingVideo)file=await _cam!.stopVideoRecording();await _startCameraSegment();_scheduleRollover();if(file!=null&&_recordingId!=null){final f=_uploadSegment(_recordingId!,file,seq);_pending.add(f);f.whenComplete((){_pending.remove(f);});}}catch(e){if(mounted)setState(()=>_error='Segment rollover failed: $e');if(_recording)_scheduleRollover();}finally{_rolling=false;}}
 void _tick(){if(!_recording||_startedAt==null)return;Future.delayed(const Duration(seconds:1),(){if(!mounted||!_recording)return;setState(()=>_elapsed=DateTime.now().difference(_startedAt!));_tick();});}
 Future<void> _uploadSegment(String rid,XFile file,int seq)async{if(mounted)setState(()=>_status='Uploading segment ${seq+1}…');final bytes=await file.readAsBytes();final pr=await ApiClient.instance.dio.post('/recordings/$rid/segments/presign',data:{'segmentIndex':seq,'contentType':'video/webm'});final pb=pr.data;final p=pb is Map&&pb['data']!=null?pb['data']:pb;if(p is! Map||p['configured']!=true||p['uploadUrl']==null||p['key']==null)throw Exception('B2 upload is not configured');final put=Dio();await put.put(p['uploadUrl'],data:Stream.fromIterable(<List<int>>[Uint8List.fromList(bytes)]),options:Options(headers:{'Content-Type':'video/webm','Content-Length':bytes.length},contentType:'video/webm'));await ApiClient.instance.dio.post('/recordings/$rid/segments',data:{'sequence':seq,'b2Key':p['key'],'sizeBytes':bytes.length,'durationSec':45});}
 Future<void> _stop()async{setState((){_busy=true;_error=null;});_segmentTimer?.cancel();try{final rid=_recordingId;if(rid==null)throw Exception('Recording id missing');XFile? file;if(_cam!=null&&_cam!.value.isRecordingVideo)file=await _cam!.stopVideoRecording();if(file!=null){final seq=_nextSequence++;final f=_uploadSegment(rid,file,seq);_pending.add(f);f.whenComplete((){_pending.remove(f);});}if(_pending.isNotEmpty){setState(()=>_status='Finishing uploads…');await Future.wait(List<Future<void>>.from(_pending));}setState(()=>_status='Queueing evidence processing…');await ApiClient.instance.dio.post('/recordings/$rid/stop',data:{'durationSec':_elapsed.inSeconds});if(!mounted)return;setState(()=>_status='Uploaded — evidence processing started');ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Recording uploaded. Evidence processing started.')));await Future.delayed(const Duration(milliseconds:600));if(mounted)Navigator.pop(context,true);}on DioException catch(e){if(mounted)setState(()=>_error=e.message??'Stop failed');}catch(e){if(mounted)setState(()=>_error='Stop failed: $e');}finally{if(mounted)setState((){_busy=false;_recording=false;});}}
 String _fmt(Duration d){final m=d.inMinutes.remainder(60).toString().padLeft(2,'0');final s=d.inSeconds.remainder(60).toString().padLeft(2,'0');final h=d.inHours;return h>0?'$h:$m:$s':'$m:$s';}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,foregroundColor:Colors.white,title:const Text('Recording Session')),body:Column(children:[Expanded(child:!_camReady?Center(child:Text(_error??'Starting camera…',style:const TextStyle(color:Colors.white70))):Stack(fit:StackFit.expand,children:[CameraPreview(_cam!),if(_recording)Positioned(top:16,left:16,child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:Colors.red.shade700,borderRadius:BorderRadius.circular(8)),child:Row(children:[const Icon(Icons.fiber_manual_record,color:Colors.white,size:14),const SizedBox(width:6),Text(_fmt(_elapsed),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700))]))),if(_status!=null)Positioned(bottom:48,left:16,right:16,child:Text(_status!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.lightGreenAccent))),if(_error!=null)Positioned(bottom:16,left:16,right:16,child:Text(_error!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.orangeAccent)))])),Container(color:Colors.black,padding:const EdgeInsets.fromLTRB(24,16,24,32),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[GestureDetector(onTap:_busy?null:_toggle,child:Container(width:72,height:72,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:Colors.white,width:4),color:_recording?AppColors.danger:Colors.white24),child:Icon(_recording?Icons.stop:Icons.fiber_manual_record,color:Colors.white,size:36)))]))]));
}
